config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  # LTI XML CONFIG
  get :lti_config, controller: :application, as: :lti_config

  # LTI LAUNCH URL (responds to get and post)
  match 'launch' => 'application#launch', via: [:get, :post], as: :lti_launch
  match '/' => 'application#launch', via: [:get, :post]

  # Link to privacy page
  get 'privacy', to: 'application#privacy', as: :lti_privacy

  # Grade callback: grades assignment
  post 'grade', to: 'application#grade', as: :lti_grade
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/controllers/application_controller.rb
# required for LTI
require 'ims/lti'
# Used to validate oauth signatures
require 'oauth/request_proxy/action_controller_request'
require 'oauth/request_proxy/rack_request'


class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # CSRF stuff ^

  # LTI Launch endpoint (responds to POST and GET - see routes.rb)
  # checks for required query params
  # checks that the oauth signature checks out
  # read more about IMS::LTI in ims-lti gem https://github.com/instructure/ims-lti
  # note the oauth nonce is not handled within ims-lti gem, it's up to you
  def launch
    authenticator = IMS::LTI::Services::MessageAuthenticator.new(
       request.url,
       request.request_parameters,
       Rails.application.config.lti_settings['consumer_secret']
     )

    if not authenticator.valid_signature?
        # the request wasnt validated :(
      render :launch_error, status: 401
      return
    end

    # The providre request is valid
    # store the values you need from the LTI
    # here we're just tossing them into the session
    session[:user_id] = params.require :user_id
    session[:lis_person_name_given] = params.require :lis_person_name_given

    # stores the result_sourceid for grade passback
    session[:lis_result_sourcedid] = params.require :lis_result_sourcedid unless params[:lis_result_sourcedid].nil?
    # stores the url for grade passback
    session[:lis_outcome_service_url] = params.require :lis_outcome_service_url unless params[:lis_outcome_service_url].nil?

    # TODO: potentially, if full marks, should store score here

    # set variables for use by the template
    @lis_person_name_given = session[:lis_person_name_given]

  end

  def grade
    correct_pts = params[:correct_pts]
    total_pts = params[:total_pts]
    session[:correct_pts] = correct_pts
    session[:total_pts] = total_pts

    reported_grade = correct_pts.to_f / total_pts
    # Cited from: https://github.com/instructure/lti_example/blob/master/lti_example.rb
    xml = %{
    <?xml version = "1.0" encoding = "UTF-8"?>
    <imsx_POXEnvelopeRequest xmlns = "http://www.imsglobal.org/lis/oms1p0/pox">
      <imsx_POXHeader>
        <imsx_POXRequestHeaderInfo>
          <imsx_version>V1.0</imsx_version>
          <imsx_messageIdentifier>12341234</imsx_messageIdentifier>
        </imsx_POXRequestHeaderInfo>
      </imsx_POXHeader>
      <imsx_POXBody>
        <replaceResultRequest>
          <resultRecord>
            <sourcedGUID>
              <sourcedId>#{params[:lis_result_sourcedid]}</sourcedId>
            </sourcedGUID>
            <result>
              <resultScore>
                <language>en</language>
                <textString>#{reported_grade}</textString>
              </resultScore>
            </result>
          </resultRecord>
        </replaceResultRequest>
      </imsx_POXBody>
    </imsx_POXEnvelopeRequest>
    }
    consumer = OAuth::Consumer.new(Rails.application.config.lti_settings['consumer_key'],  Rails.application.config.lti_settings['consumer_secret'])
    token = OAuth::AccessToken.new(consumer)
    response = token.post(params[:lis_outcome_service_url], xml, 'Content-Type' => 'application/xml')
    
    if response.body.match(/\bsuccess\b/)
      render :json => { success: 1, numCorrect:  correct_pts, numTotal: total_pts}
    else 
      render :json => { success: 0, numCorrect:  0, numTotal: 0}
      return
    end
  end 

  # lTI XML Configuration
  # Used for easily installing your LTI into an LMS
  def lti_config
    render template: "application/lti_config.xml"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/launch_helper.rb
module LaunchHelper
end

app/helpers/xml_helper.rb
module XmlHelper
end

app/views/application/index.html.erb
<h1>BoomBridge</h1>

<h2>What is BoomBridge?</h2>
<p>We created BoomBridge to help address the disconnection between Canvas and BoomCards. It is a Canvas plug-in that processes student-submitted BoomCards screenshots and automatically grades the corresponding Canvas assignments.</p>


<h2>Configuring the Canvas Plug-in</h2>
<p>
    We designed this tool to work with any learning management tool that supports Learning Tools Interoperability (LTI). The tool is optimized for Canvas as it is the current learning management system used at Red Cloud. BoomBridge needs to be configured with each Canvas course. The following are instructions for loading BoomBridge as an External App in Canvas.
</p>
<ol>
    <li>Go to your Canvas course and click on Settings > Apps > View App Configurations. Then click on “+App” to add a new External App.
    <li>
        Fill in the Name, Consumer Key, and Shared Secret as shown below. Set the Privacy to Public.
        <ol style="list-style-type: lower-alpha; padding-bottom: 0;">
            <li style="margin-left:2em">
                You should change the consumer key and shared secret if you have changed them on the server’s “config/lti_settings.yml” file.
            </li>
            <li style="margin-left:2em; padding-bottom: 0;">
                If you have migrated from the CMU-hosted server to your on-premise server, you should use the domain pointing to that server for the launch URL. For example, if your domain name is apple.com, then your new launch URL should be “https://apple.com/launch"
            </li>
            <li style="margin-left:2em; padding-bottom: 0;">
                You must set the privacy setting to Public.
            </li>
        </ol>
    </li>
    <li>Finally, click “Submit”.</li>
</ol>

<h2>LTI Launch</h2>

<p>View the LTI Launch endpoint <a href="<%= lti_launch_path %>" data-turbolinks="false">here</a></p>

<p>Note, this URL is typically sent a POST request with all sorts of LTI data. If you access it directly, it'll display an error page indicating your request did not validate.</p>

<h3><a href="<%= lti_privacy_path %>" style="color: white;" data-turbolinks="false"> Privacy Policy</a></h3>

app/views/application/launch.html.erb
<!-- Welcome Section -->
<div id="welcome-section" style="display:none;">
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-a11y="true"></script>
    <%= javascript_tag do %>
    var lis_result_sourcedid = "<%= session[:lis_result_sourcedid] %>";
    var lis_outcome_service_url = "<%= session[:lis_outcome_service_url] %>";
    <% end %>
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.4.0/dist/confetti.browser.min.js"></script>
    <div class="greeting">
        <h1>
            <span class="eng">Hi, <%= @lis_person_name_given %></span>
            <span class="lkt">Hau, <%= @lis_person_name_given %></span>
            <div id="translate">
                <%= image_tag "icons/icon_switch.png", id: 'translate-icon' %>
                <!--- note this lkt - eng inverse is intentional --->
                <span class="lkt">English</span>
                <span class="eng">Lakȟótiyapi</span>
            </div>
        </h1>


    </div>
    <div>
        <h2 class="subtitle" style="margin-bottom: 0.3rem;">
            <%= image_tag "icons/icon_screenshot.png", class: "heading-icon"%>
            <span class="text eng">Screenshot Your Boom Cards</span>
            <span class="text lkt">Boom Cards kiŋ itówapi ikíkču wo/we</span>
        </h2>
        <h3 class="caption leading-margin">
            <span class="eng">Screenshot the results page for your assigned Boom Cards deck.</span> <br class="eng" />
            <span class="eng">Make sure they look like these:</span>
            <span class="lkt">Tókhel ečhánuŋ k’uŋ itówapi ikíkču na ečhél Boom Cards kȟaŋsú etáŋ nič’úpi kte.</span> <br class="lkt" />
            <span class="lkt">Léčheča kte héčha:</span>
        </h3>
        <img class="sample-image leading-margin" src="correct.png" height="200" alt="Correct">
        <img class="sample-image leading-margin" src="wrong.png" height="200" alt="Wrong">
        <h2 class="subtitle">
            <%= image_tag "icons/icon_upload.png", class: "heading-icon" %>
            <span class="eng">Submit here</span>
            <span class="lkt">Lél iyáyeya yo/ye</span>
        </h2>

        <div class="leading-margin">
            <input type="file" id="upload" accept=".png, .jpg, .jpeg" hidden onclick="this.value=null;" />
            <label for="upload">
                <div class="upload-container" id="upload-container">
                    <%= image_tag "icons/icon_photo.png", id: 'icon-photo' %> <br>
                    <span class="upload-label eng">Click to Upload</span>
                    <!--check this translation-->
                    <span class="upload-label lkt">Waŋkál okšú kta akákpi yo/ye</span>
                </div>
            </label>
        </div>
    </div>
</div>

<!-- Processing (Spinner) Section -->
<div id="processing-section" class="text-center" style="display:none;">
    <h1>
        <span class="eng">Unwrapping Your Gift...</span>
        <span class="lkt">Wak’úpi Yaglúžužu (kte)...</span>
    </h1>

    <div class="margin-center">
        <%= image_tag "icons/icon_gift.png", id: "icon_gift" %>
        <div class="loader"></div>
    </div>
</div>

<!-- Result Section -->
<div id="result-section" class="text-center" style="display: none;">
    <div id="partial-credit-page" style="display: none;">
        <h1 id="partial-credit-page-note"></h1>

        <h2 class="completion-subheading">
            <span class="eng">The next lesson might be unlocked.</span>
            <!--- TODO: add translation ---->
            <span class="lkt">Owáuŋspe iyókhihe kiŋ yuǧáŋ-hiŋ kte séče.</span>
        </h2>

        <div class="text-center card-button">
            <%= image_tag "icons/icon_reload.png", class: 'icon-reload'%>
            <h5 class="card-button-label">
                <span class="eng">New Attempt</span>
                <span class="lkt">Iyútȟapi Lečhála</span>
            </h5>
        </div>
    </div>

    <div id="wrong-image-page" style="display: none;">
        <h1>
            <span class="eng">Uh oh, no gift &#128577;</span>
            <span class="lkt">Akšáka, wak’úpi waníče &#128577;</span>
        </h1>
        <h2 class="completion-subheading" id="wrong-image-page-note">
            <span class="eng">Perhaps you turned in the wrong screenshot. Try again.</span>
            <span class="lkt">Itówapi héčhetu šni waŋ iyáyeyayiŋ kte séče. Akhé iyútȟa yo/ye.</span>
        </h2>

        <div class="text-center card-button">
            <%= image_tag "icons/icon_reload.png", class: 'icon-reload'%>
            <h5 class="card-button-label">
                <span class="eng">Try Again</span>
                <span class="lkt">Akhé iyútȟa yo/ye</h5>
            </h5>
        </div>
    </div>


    <div id="full-marks-page" style="display: none;">
        <h1 id="gift"></h1>
        <h5 class="completion-subheading" id="full-marks-page-note">Your score is <%= session[:correct_pts] %> / <%= session[:total_pts]%>!</h5>

    </div>
</div>

app/views/application/launch_error.html.erb
<h1>Error!</h1>
<p>Authentication error, please refresh and try again. If the error pursues, please contact support.</p>

app/views/application/lti_config.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<cartridge_basiclti_link xmlns="http://www.imsglobal.org/xsd/imslticc_v1p0"
    xmlns:blti = "http://www.imsglobal.org/xsd/imsbasiclti_v1p0"
    xmlns:lticm ="http://www.imsglobal.org/xsd/imslticm_v1p0"
    xmlns:lticp ="http://www.imsglobal.org/xsd/imslticp_v1p0"
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "http://www.imsglobal.org/xsd/imslticc_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticc_v1p0.xsd
    http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0.xsd
    http://www.imsglobal.org/xsd/imslticm_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticm_v1p0.xsd
    http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd">
    <blti:title>LTI Name</blti:title>
    <blti:description>LTI Description</blti:description>
    <blti:icon></blti:icon>
    <blti:launch_url><%= lti_launch_url  %></blti:launch_url>
    <blti:extensions platform="canvas.instructure.com">
      <lticm:property name="tool_id">ID</lticm:property>
      <lticm:property name="privacy_level">public</lticm:property>
      <lticm:options name="course_navigation">
        <lticm:property name="url"><%= lti_launch_url %></lticm:property>
        <lticm:property name="text">BoomBridge</lticm:property>
        <lticm:property name="visibility">admins</lticm:property>
        <lticm:property name="default">enabled</lticm:property>
        <lticm:property name="enabled">true</lticm:property>
      </lticm:options>
    </blti:extensions>
    <cartridge_bundle identifierref="BLTI001_Bundle"/>
    <cartridge_icon identifierref="BLTI001_Icon"/>
</cartridge_basiclti_link>

app/views/application/privacy.html.erb
<h1>Privacy Policy</h1>

<h2>The Data We Collect</h2>
<p>BoomBridge collects no data. In other words, the application does not permanently store any data (except in memory to support user activities while they are interacting with this tool).</p>

<h2>The Data We Process</h2>
<p>We process encrypted student and course information using the Canvas LTI APIs. Additionally, we process student screenshots on-device to extract grading information. We only send the extracted grades to our servers. Student uploaded screenshots are never sent to our servers and is kept strictly in the cache on their local machines.</p>

<h2>How We Protect Your Data</h2>
<p>At BoomBridge, we believe that privacy is a fundamental human right. We protect your data in the following ways:</p>
<ul>
    <li>Data Minimization: we only collect the data we need to deliver the services provided by this tool.</li>
    <li>On-Device Processing: we use on-device machine learning to recognize grade information from screenshots. Student-submitted screenshots never leave their devices.</li>
    <li>Control: this LTI tool can be easily disconnected from Canvas.</li>
    <li>Data Security: student data is encrypted in both directions when we communicate with Canvas using a private key </li>
</ul>

<h2>Your Obligations with Respect to Children and Students</h2>
<p>Educators are allowed to connect this app to Canvas via the LTI plug-in feature. We treat the process of adding this app to Canvas as a verification of the adult status of the person adding the plug-in (Administrator).</p>
<p>As an Administrator of the plug-in, you must have the legal right to set up this plug-in for students enrolled in your Canvas course(s), such as being the parent or legal guardian of a student, the right to act in parentis loci under the Family Educational Rights and Privacy Act (FERPA) (as required by the Children’s Online Privacy Protection Act), or a signed consent from the parent or legal guardian of the student.</p>
<p>Schools agree and understand that their legal right to engage BoomBridge to process student data on their behalf arises under the school official exception of FERPA. Pursuant to that exception, BoomBridge performs a service for which a school would otherwise use employees and BoomBridge operates under the control of the school with respect to the use and maintenance of education records for a legitimate education interest. BoomBridge uses student data solely for the purpose of fulfilling our duties and providing and improving services under this agreement.</p>

<h2>Vendors Privacy</h2>
<p>The usage of this app depends on two external Vendors: Canvas and Boom Cards. Tools provided by both Vendors are FERPA compliant. Please refer to their respective privacy policy documentation for more details:</p>
<ul>
    <li>Canvas: <a href="https://www.instructure.com/policies/privacy">Canvas Privacy Policy</a></li>
    <li>Boom Cards / Boom Learning: <a href="https://wow.boomlearning.com/blog/privacy">Boom Learning Privacy Policy</a></li>
</ul>

app/views/layouts/_footer.html.erb
    <footer>
        <p>Built using the <a href="https://github.com/ucfopen/lti-template-rails">UCF LTI Template for Rails</a> 2016 &ndash; <%= Date.today.year %></p>
    </footer>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en-US">

<head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://unpkg.com/tesseract.js@v2.0.2/dist/tesseract.min.js' %>

    <title>BoomBridge</title>
</head>

<body>

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
<%= yield %>